# Generated by Django 4.1.2 on 2023-04-25 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'ApplicationStatus',
            },
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ApplicationType',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('deleteDate', models.DateTimeField(null=True)),
                ('file', models.FileField(upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Document',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('applicationData', models.JSONField()),
                ('documents', models.ManyToManyField(db_table='ApplicationDocuments', related_name='applications', to='applications.document')),
                ('receiverUserId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_applications', to=settings.AUTH_USER_MODEL)),
                ('senderUserId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_applications', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.applicationstatus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.applicationtype')),
            ],
            options={
                'db_table': 'Application',
            },
        ),
    ]
