# Generated by Django 4.1.1 on 2023-01-16 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('capacity', models.IntegerField(blank=True, db_index=True)),
            ],
            options={
                'db_table': 'BusType',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nativeName', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'Language',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coordinates', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='ResourceCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'ResourceCode',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.TimeField(db_index=True)),
                ('distance', models.FloatField()),
                ('destination', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='tickets.location')),
                ('source', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='source', to='tickets.location')),
            ],
            options={
                'db_table': 'Route',
            },
        ),
        migrations.CreateModel(
            name='ResourceValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('language_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.language')),
                ('nameCode_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.resourcecode')),
            ],
            options={
                'db_table': 'ResourceValue',
            },
        ),
        migrations.CreateModel(
            name='PostTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.IntegerField(blank=True, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('route_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='tickets.route')),
            ],
            options={
                'db_table': 'PostTicket',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='nameCode_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.resourcecode'),
        ),
        migrations.AddField(
            model_name='language',
            name='resourcecode_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.resourcecode'),
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('availableCapacity', models.IntegerField(blank=True, db_index=True)),
                ('type_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.bustype')),
            ],
            options={
                'db_table': 'Bus',
            },
        ),
    ]
