# Generated by Django 4.1.1 on 2023-01-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportNumberType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(db_index=True, max_length=255)),
                ('format', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'PassportNumberType',
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'TicketStatus',
            },
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='resourcecode_id',
            new_name='resourcecode',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='nameCode_id',
            new_name='nameCode',
        ),
        migrations.RenameField(
            model_name='postticket',
            old_name='route_id',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='resourcevalue',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='resourcevalue',
            old_name='nameCode_id',
            new_name='nameCode',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='TicketPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_index=True, max_length=255)),
                ('lastName', models.CharField(db_index=True, max_length=255)),
                ('secondName', models.CharField(db_index=True, max_length=255)),
                ('passportNumber', models.CharField(db_index=True, max_length=255)),
                ('passportNumberType', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.passportnumbertype')),
            ],
            options={
                'db_table': 'TicketPerson',
            },
        ),
        migrations.AddField(
            model_name='postticket',
            name='person',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='tickets.ticketperson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postticket',
            name='status',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.PROTECT, to='tickets.ticketstatus'),
            preserve_default=False,
        ),
    ]
