# Generated by Django 4.1.2 on 2023-03-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_bus_availablecapacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduletype',
            old_name='nameCodeId',
            new_name='nameCode',
        ),
    ]
