# Generated by Django 4.1.2 on 2023-05-08 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(db_index=True, max_length=255)),
                ('firstName', models.CharField(blank=True, db_index=True, max_length=255)),
                ('lastName', models.CharField(blank=True, db_index=True, max_length=255)),
                ('birthDate', models.DateField(blank=True, db_index=True, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=False)),
                ('isDeleted', models.BooleanField(blank=True, default=False)),
                ('isVerified', models.BooleanField(blank=True, default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('verificationCode', models.CharField(blank=True, max_length=255)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Customer'), (3, 'Guide'), (4, 'Business Person')], null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serviceRating', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Guide',
            },
        ),
        migrations.CreateModel(
            name='GuideSpecialization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('isMain', models.BooleanField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authorization.guide')),
            ],
            options={
                'db_table': 'GuideSpecialization',
            },
        ),
        migrations.CreateModel(
            name='BusinessPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=255)),
                ('binNumber', models.CharField(max_length=12)),
                ('legalAddress', models.CharField(max_length=255)),
                ('serviceRating', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BusinessPerson',
            },
        ),
    ]
