# Generated by Django 4.1.1 on 2022-10-19 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coordinates', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.TimeField(db_index=True)),
                ('distance', models.FloatField()),
                ('destination', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='authorization.location')),
                ('source', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='source', to='authorization.location')),
            ],
        ),
        migrations.CreateModel(
            name='PostTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='authorization.route')),
            ],
        ),
    ]
