# Generated by Django 4.1.1 on 2022-10-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_location_route_postticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='postticket',
            name='cost',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
