# Generated by Django 4.1.1 on 2022-10-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_postticket_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
