# Generated by Django 4.1.1 on 2022-10-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_remove_user_role_id_delete_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postticket',
            name='route_id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='route',
            name='source',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='PostTicket',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
